In [5]:
import numpy as np
import pandas as pd
from pandas import DataFrame

In [29]:
df = pd.read_csv(r"2022 Sixt - Commercial Analytics Recruiting Task.csv", header = 0, delimiter=';')

In [30]:
df.head()

Client FirstAction LastAction        Date      Time  \
0  ws014855    14:44:59   14:45:15  16.09.2014  14:45:15   
1  ws014855    17:20:48   17:20:59  25.09.2014  17:20:59   
2  ws014855    15:38:00   15:39:01  11.09.2014  15:38:13   
3  ws014855    16:19:01   16:19:01  22.09.2014  16:19:01   
4  ws014855    13:07:30   13:07:56  29.09.2014  13:07:52   

                         UserID     UserAction     ArtNr  \
0  User94295555912ID99912263546         liftup  598886.0   
1  User91580650629ID43569660373  starttut_auto  574296.0   
2  User14958227612ID93909495044  starttut_auto  558355.0   
3  User46918181749ID43074807525         liftup  596579.0   
4  User18960750848ID74810983101         liftup  572848.0   

                       ArtName  Place   Price ActionInfo1  CompareArtNr  \
0          Rolex GMT-Master II      2  9735.0         NaN           NaN   
1  Maurice Lacroix Retrogrades      1  5985.0         NaN           NaN   
2     Rol Die Sea-Dweller 4000      5  6435.0         NaN           NaN   
3   Breitling Chronomat B13350     13  5985.0         NaN           NaN   
4    Rolex Die Dweller 3500 CH      7  5235.0         NaN           NaN   

   ComparePlace ShopType  
0           NaN        C  
1           NaN        C  
2           NaN        C  
3           NaN        C  
4           NaN        C

In [31]:
df.dtypes

Client           object
FirstAction      object
LastAction       object
Date             object
Time             object
UserID           object
UserAction       object
ArtNr           float64
ArtName          object
Place             int64
Price           float64
ActionInfo1      object
CompareArtNr    float64
ComparePlace    float64
ShopType         object
dtype: object

In [ ]:
    'FirstAction': time,
    'LastAction': time,
    'Date': date,
    'Time': time,

In [36]:
convert_dict = {
    'Client': str, 
    'UserID': str,
    'UserAction': str,
    'ArtNr': int,
    'ArtName': str,
    'Place': int,
    'Price': float,
    'ActionInfo1': int,
    'CompareArtNr': int,
    'ComparePlace': int,
    'ShopType': str,
}

In [37]:
df1 = df.astype(convert_dict)
df1

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [38]:
df0.describe()

ArtNr          Place          Price   CompareArtNr  \
count  182695.000000  182703.000000  182695.000000   10998.000000   
mean   587725.350924      10.327953    6094.797750  588476.615839   
std     17578.757372       6.250410    3376.476174   17506.659479   
min    543700.000000       1.000000    1485.000000  543700.000000   
25%    574296.000000       5.000000    2535.000000  577349.000000   
50%    596579.000000       9.000000    5985.000000  598044.000000   
75%    602302.000000      16.000000    9735.000000  602302.000000   
max    605751.000000      27.000000   11235.000000  605751.000000   

       ComparePlace  
count  10998.000000  
mean      10.929442  
std        6.072575  
min        1.000000  
25%        5.000000  
50%       11.000000  
75%       16.000000  
max       21.000000

In [39]:
df[df.duplicated()]

Empty DataFrame
Columns: [Client, FirstAction, LastAction, Date, Time, UserID, UserAction, ArtNr, ArtName, Place, Price, ActionInfo1, CompareArtNr, ComparePlace, ShopType]
Index: []

In [40]:
df.isna().sum()

Client               0
FirstAction          0
LastAction           0
Date                 0
Time                 0
UserID               0
UserAction           0
ArtNr                8
ArtName              8
Place                0
Price                8
ActionInfo1     158127
CompareArtNr    171705
ComparePlace    171705
ShopType          3575
dtype: int64

In [41]:
df.nunique()

Client             89
FirstAction     29501
LastAction      29336
Date               30
Time            43063
UserID          53331
UserAction          8
ArtNr              22
ArtName            22
Place              23
Price              12
ActionInfo1        43
CompareArtNr       22
ComparePlace       21
ShopType            6
dtype: int64

In [ ]:
df[]

In [44]:
df['ArtNr'].unique()

array([598886., 574296., 558355., 596579., 572848., 577349., 585655.,
       605750., 581108., 543700., 572847., 603064., 601509., 602302.,
       605751., 603048., 572849., 593879., 605712., 598044., 605658.,
       579413.,     nan])

In [45]:
df['Place'].unique()

array([ 2,  1,  5, 13,  7, 17, 11,  8, 21,  3, 14,  4, 15, 12, 19, 16,  6,
       18, 20,  9, 10, 27, 24], dtype=int64)

In [46]:
df['CompareArtNr'].unique()

array([    nan, 558355., 543700., 598886., 577349., 581108., 602302.,
       605658., 572848., 572847., 603048., 593879., 603064., 598044.,
       605751., 605750., 579413., 601509., 585655., 596579., 572849.,
       574296., 605712.])